AWSTemplateFormatVersion: 2010-09-09
Description: Resource needed for the backend

Resources:

  DotHiddenEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: dothidden
  
  

Outputs:

  DotHiddenEcrRepoArn:
    Value: !GetAtt DotHiddenEcrRepo.Arn
    Export:
      Name: DotHiddenEcrRepo
