version: '3'

services:

  dothidden:
    build: .
    image: dothidden_server
    container_name: dothidden_server
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    networks:
      - dothidden_network

networks:

  dothidden_network:
    name: dothidden_network
    driver: bridge

volumes:

  dothidden_volume:
