name: Frontend

on:
  push:
    paths:
    - 'client/**'
    branches: 
    - main 

  pull_request:
    paths:
    - 'client/**'
    branches:
    - main

  workflow_dispatch:

jobs:

  deploy:

    name: Backend pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server/

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14

      - run: npm install

      - run: npm run lint

